openapi: '3.0.2'
info:
  title: CO2 Emissions API.
  version: '1.0'
  description: |
    Design API for a web application used to see and update a database related to CO2
    and greenhouose gases emissions.

servers:
  - url: http://localhost:8080
    description: Spring Boot backend implementation.

components:
  schemas:
    $ref: "schemas.yaml"

  responses:
    $ref: "reponses.yaml"

  parameters:
    order-by-alpha:
      name: order-by-alpha
      in: query
      required: false
      description: The column to order the result data by alphabetically
      schema:
        $ref: "#/components/schemas/CountryFilterKeysAlpha"

    order-by-num:
      name: order-by-num
      in: query
      required: false
      description: The column to order the result data by numbers
      schema:
        $ref: "#/components/schemas/CountryFilterKeysNum"

    order-dir:
      name: order-dir
      in: query
      required: false
      description: The directorion to order the indicated column
      schema:
        type: string
        enum:
          - desc
          - asc

    order-by-year:
      name: order-by-year
      in: query
      required: false
      description: The column to order the result data by years
      schema:
        $ref: "#/components/schemas/DataFilterKeys"

    limit:
      name: limit
      in: query
      required: true
      description: Limit the number of returned items
      schema:
        type: integer
        maximum: 100

    offset:
      name: offset
      in: query
      required: false
      description: The number of items to skip before returning {limit} items
      schema:
        type: integer

paths:
  /countries:
    get:
      tags:
        - Countries
      summary: Retrives a list of countries.
      description: Retrieves a list of countries (their name and ISO code).
      parameters:
        - $ref: "#/components/parameters/order-by-alpha"
        - $ref: "#/components/parameters/order-by-num"
        - $ref: "#/components/parameters/order-dir"
        - $ref: "#/components/parameters/limit"
        - $ref: "#/components/parameters/offset"
      
      responses:
        "200":
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CountrySummary"
            text/csv:
              schema:
                $ref: "#components/schemas/CountrySummary"
              example: |-
                name,ISO
                string, string 

        '204':
          $ref: "#/components/responses/NoResults"

        '400':
          $ref: '#/components/responses/BadRequest'

        '5XX':
          $ref: '#/components/responses/ServerError'

  /countries/{ISO}/:
    get:
      tags:
        - Countries
      summary: Retrives the summary of a country.
      description: Retrieves the summary of a specific country. The country is picked based on ISO code.
      responses:
        "200":
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref : "#components/schemas/CountrySummary"
            text/csv:
              schema:
                $ref: "#components/schemas/Country"
              example: |-
                name,ISO
                string,string


        '204':
          $ref: "#/components/responses/NoResults"

        '400':
          $ref: '#/components/responses/BadRequest'

        '5XX':
          $ref: '#/components/responses/ServerError'

    post:
        tags:
          - Countries
        summary: Creates a new country data entry.
        description: Creates a new data entry for a country, specified by ISO code.
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Data"
        responses:
          '201':
            description: Country data successfully created
            content:
              application/json:
                schema:
                  type: integer
                  description: The year of the newly created data.
              text/csv:
                schema:
                  type: integer
                  example: |-
                    year
                    2000

          '400':
            $ref: '#/components/responses/BadRequest'

          '409':
            description: Entry with the same year already exists

          '5XX':
            $ref: '#/components/responses/ServerError'

  /countries/{ISO}/generalData:
    parameters: 
      - name: ISO
        in: path
        required: true
        description: ISO of the country
        schema:
          type: string
        
    get: 
      tags: 
        - Countries
      summary: Retrives a list of years for General Data
      description: Retrives the list of years in which this country has a General Data. The selected country is based on the ISO Code.
      responses: 
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
            text/csv:
              schema:
                type: array
                items:
                  type: integer
              example: |-
                years
                1990
                1991
                1992

        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref:  "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'

  /countries/{ISO}/generalData/{year}:
    parameters:
      - name: ISO
        in: path
        required: true
        description: ISO of the country
        schema:
          type: string
      - name: year
        in: path
        required: true
        description: year of the GeneralData
        schema:
          type: integer

      
    get:
      tags:
        - Countries
      summary: Retrieves the General Data for a country.
      description: Retrives the General Data for a contry (based on ISO) in a specific year.
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralData"

            text/csv:
              schema:
                $ref: "#components/schemas/GeneralData"
              example: |-
                population,GDP,ownerName
                0,0,string

        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref:  "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'

    put:
      tags:
        - Countries
      summary: Update General Data for a country.
      description: Updates the General Data for a country (based on ISO) in a specific year.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeneralData"
      responses:
        '200':
          description: Country updated, returns the new state
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GeneralData"
            text/csv:
              schema:
                $ref: "#/components/schemas/GeneralData"
              example: |-
                population,GDP,ownerName
                0,0,string


        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref: "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'

    delete:
      tags:
        - Countries
      summary: Delete General Data for a country.
      description: Delete the General Data for a country (based on ISO) in a specific year.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GeneralData"
      responses:
        '204':
          description: "Deleted data for a country"
          
        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref: "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'



  /contries/{ISO}/emissionsData:
    parameters:
      - name: ISO
        in: path
        required: true
        description: ISO of the country
        schema:
          type: string
    get:
      tags:
        - Countries
      summary: Retrieve emmision data
      description: Retrieves emmission data with from specified country
      parameters: 
        - $ref: "#/components/parameters/order-by-alpha"
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EmissionData"
            text/csv:
              schema:
                $ref: "#components/schemas/GeneralData"
              example: |-
                CO2,CH4,N20,total_ghg,ownerName
                0,0,0,0,string


        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref:  "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'


  /continents:
    get:
      tags:
        - Continents
      summary: Retrieves a list of continents
      description: Retrieves a list of continents with their name and data
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ContinentSummary"
            text/csv:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ContinentSummary"
              example: |-
                name
                string
        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref:  "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'


  /continents/{name}:

    get:
      tags:
        - Continents
      summary: "Retrieves a continent"
      description: "Retrieves a continent with specified name"
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/DataSummary"
            text/csv:
              schema:
                 $ref: "#/components/schemas/DataSummary"
              example: |-
                generalData,emissionData,temperatureData,energyData
                string,string,string,string

        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref:  "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'


  /continents/{name}/temperatureData:

    get:
      tags:
        - Continents
      summary: "Retrieves temperature data"
      description: "Retrieves temperature data for a specified continent"
      parameters: 
        - $ref: "#/components/parameters/order-by-alpha"
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                  $ref: "#/components/schemas/TemperatureData"
            text/csv:
              schema:
                  $ref: "#/components/schemas/TemperatureData"
              example: |-
                shares_of_temp_change_from_ghg,temperature_change_CH4,temperature_change_N20,temperature_change_CO2,temperature_change_ghg,ownerName
                0,0,0,0,0,string


        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref:  "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'
          
  /years:
    get: 
      tags: 
        - Years
      summary: Retrieves list of years 
      description: Retrieves list of years with avalible data
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  type: integer
            text/csv:
              example: |-
                years
                1990
                1991
                1992


        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref:  "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'  

  /years/{year}:
    parameters:
      - name: year
        in: path
        required: true
        description: specific year
        schema:
          type: integer

    get: 
      tags: 
        - Years
      summary: Retrieves data avalible for specific year 
      description: Retrieves data avalible for specific year
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DataSummary"
            text/csv:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DataSummary"
              example: |-
                generalData,emissionData,temperatureData,energyData
                string,string,string,string

        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref:  "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'           
          
  /years/{year}/energyData:
    parameters:
      - name: year
        in: path
        required: true
        description: specific year
        schema:
          type: integer

    get: 
      tags: 
        - Years
      summary: Retrieves Energy Data 
      description: Retrieves Energy Data for a specific year
      parameters:
        - $ref: "#/components/parameters/order-by-num"
      responses:
        '200':
          description: Successful retrieval
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnergyData"
            text/csv:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/EnergyData"
              example: |-
                energy_per_cap,energy_per_ghg,ownerName
                0,0,string

        '400':
          $ref: '#/components/responses/BadRequest'

        '404':
          $ref:  "#/components/responses/NotFound"

        '5XX':
          $ref: '#/components/responses/ServerError'           
          